# github workflow for KernelCI for rootfs building
# command /buildrootfs in PR will trigger this job
name: pull request rootfs build command
on:
  #issue_comment:
  #  types: [created]
  push:
    branches:
      - github-rootfs-build
jobs:
  #if: contains(github.event.comment.html_url, '/pull/') && contains(github.event.comment.body, '/buildrootfs')
  #if: contains(github.event.comment.body, '/buildrootfs')
  runs-on: ubuntu-22.04
  steps:
    - name: Checkout kernelci-deploy
      uses: actions/checkout@v4
      with:
        repository: kernelci/kernelci-deploy
        path: kernelci-deploy
        branch: main
    - name: Checkout
      uses: actions/checkout@v4
      with:
        submodules: recursive
        fetch-depth: 0
        path: kernelci-deploy/tools/kernelci-core
    - name: Prepare necessary tools
      run: |
        sudo apt-get update
        sudo apt-get install -y python3-pip git
    - name: run rootfs build
      run: |
        cd kernelci-deploy/tools;./kci-rootfs.py --arch arm64,amd64 --name bookworm

